### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ghost** [oz123/blogit#1]
Hello Oz,

I'm happy to see and [read](https://oz123.github.io/writings/2008-08-11-wordpress-rantor-may-be-rants/) that you've continued someone else project.

The main reason to start [learning python](https://wifiextender.github.io/post/5th-day-with-python/) 2 years ago was because I stumbled across a project that opened my eyes and lowered the barriers and dependencies about having static blog without any requirements for the host.

I didn't knew that I will end up creating my own [static website generator](https://github.com/wifiextender/blogfy) from scratch.

I like your blog and GitHub projects.

Cheers

**Comment by oz123** [comment]
WTF?
